# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            ferronordic.d-velop:
                base_uri: 'https://ferronordic.d-velop.cloud/'
                headers:
                    Content-Type: 'application/json'
                    User-Agent: 'PostmanRuntime/7.26.5'
                    Accept: '*/*'
                    Accept-Encoding: 'gzip, deflate, br'
                    Connection: 'keep-alive'
                    Authorization: 'Bearer EqDRIfh1AKsFY8gvppYslg1Js1tYplcpyvH0c0svzfoLf3WA6RlgTBb6uvGRcwTRrWKACpAL9iLcaR5OIAlz6M9jFoG94wIIUNUBJUIBSO8=&_z_A0V5ayCT-hUTe1PPR0h3SrYprhlOnuZtTKZnFbO6z5_cc4bXy778pqxAcF44XONPpTzGUd2TdkJVVRcvHNSrfYk6LFgJh'