nelmio_api_doc:
    documentation:
        info:
            title: Alles Schrott!
            description: This is an awesome app! (ironie)
            version: -5.7.0
    # config/packages/nelmio_api_doc.yaml

    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)